name: weather_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  bloc_test: ^9.1.7
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  datetime_loop: ^1.2.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.5
  flutter_screenutil: ^5.9.0
  geocode: ^1.0.3
  geolocator: ^11.0.0
  get_it: ^7.7.0
  http: ^1.2.1
  internet_connection_checker_plus: ^2.2.0
  intl: ^0.19.0
  mocktail: ^1.0.3
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  sliver_sticky_collapsable_panel: ^2.0.6
  svg_flutter: ^0.0.1
  very_good_analysis: ^5.1.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
